---
name: Proposed Change
about: Suggest a change or improvement to the project
---

## Proposed Change

### Description

<!-- Provide a brief description of the proposed change -->

### Motivation

<!-- Explain why this change is necessary -->

### Does NOT reduce survivor governance authority
- [ ] Does NOT introduce evidentiary media ingestion, storage, or management
- [ ] Does NOT introduce cross-linkage of intake streams by default

### Related issues

<!-- Link related issues, if any -->

### Checklist
- [ ] Changes have been tested
- [ ] Documentation has been updated
- [ ] Code follows the project's coding standards
- [ ] My code has been reviewed by at least one other contributor
