# Proposed Change Issue Template

## Guardrail Checklist
- Does NOT introduce new investigative powers
- Does NOT introduce bulk data ingestion  
- Does NOT introduce biometric scraping, facial recognition, or watchlists  
- Does NOT introduce risk scoring, profiling, or predictive policing  
- Does NOT introduce mass surveillance or monitoring  
- Does NOT introduce automated referral to law enforcement without human validation  
- Does NOT remove or weaken mandatory human-in-the-loop requirements  
- Does NOT reduce survivor governance authority  
- Does NOT introduce evidentiary media ingestion, storage, or management  
- Does NOT introduce cross-linkage of intake streams by default
